spring:
  profiles:
    active: "k8s"

myapplication:
  name: "loggingDemo"
  author: "facundo-ramallo"
  logging:
    headers: "PublisherId;ApiKey"
    all-headers: ${headers}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Madrid

logback.access:
    enabled: true
    config: "classpath:logback-access-spring.xml"
    local-port-strategy: local

server:
  tomcat:
    accesslog:
      enabled: true

debug: false