spring:
  profiles:
    active: dev

myapplication:
  name: "loggingDemo"
  author: "facundo-ramallo"

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Madrid

server:
  tomcat:
    accesslog:
      enabled: true

debug: false